# Generated by Django 4.1.4 on 2022-12-26 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapiapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proj_name', models.CharField(max_length=100)),
                ('manager_name', models.CharField(max_length=20)),
                ('desc', models.CharField(max_length=200)),
            ],
        ),
    ]
