# Generated by Django 4.1.4 on 2022-12-31 17:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restapiapp', '0005_teammember_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='manager_email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='proj_end_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='proj_start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
