# Generated by Django 4.1.4 on 2023-01-07 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapiapp', '0009_myproject_myteammember_myteam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myteammember',
            name='team_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapiapp.myteam'),
        ),
    ]
