# Generated by Django 4.1.4 on 2022-12-28 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapiapp', '0003_team_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='team_name',
            field=models.CharField(default='team name', max_length=50),
        ),
    ]
